/*
  Autoškola TOP icon set. Drawn from the logo's geometry rather than a stock library:
  heavy 2.5 strokes with flat ends and sharp corners (like the condensed AUTOŠKOLA caps),
  free ends cut at 37 degrees (the wing-tip angle), and the stepped wing stripes as motif.
  One accent element per icon uses --icon-accent (the orange of the "Rakovník" signature).
  Generated by scripts/icons/gen.py (python scripts/icons/gen.py); edit geometry there, not by hand.
*/
import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  size?: number | string;
  /** Accessible name. Without it the icon is decorative (aria-hidden). */
  title?: string;
};

function Svg({ size = 24, title, children, ...props }: IconProps & { children: React.ReactNode }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={2.5}
      strokeLinecap="butt"
      strokeLinejoin="miter"
      strokeMiterlimit={10}
      role={title ? "img" : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      focusable="false"
      {...props}
    >
      {children}
    </svg>
  );
}

export function IconCheck(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M3.5 12.5 9.5 18.5 20.5 6" />
    </Svg>
  );
}

export function IconCheckTile(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2 2H22V17.5L16 22H2Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M6.5 12 10.5 16 17.5 8.5" stroke="var(--icon-knock, var(--bg))" />
    </Svg>
  );
}

export function IconClose(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M5 5 19 19M19 5 5 19" />
    </Svg>
  );
}

export function IconPlus(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M12 4V20M4 12H20" />
    </Svg>
  );
}

export function IconMenu(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M3 5H21V7.5H6.325Z" fill="currentColor" stroke="none" /><path d="M7 10.75H21V13.25H10.325Z" fill="currentColor" stroke="none" /><path d="M11 16.5H21V19H14.325Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconArrowRight(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M3 12H19.5M13.5 5.5 20 12 13.5 18.5" />
    </Svg>
  );
}

export function IconArrowLeft(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M21 12H4.5M10.5 5.5 4 12 10.5 18.5" />
    </Svg>
  );
}

export function IconArrowUpRight(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M5.5 18.5 17.5 6.5M8 5.5H18.5V16" />
    </Svg>
  );
}

export function IconCaretDown(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M5 8.5 12 15.5 19 8.5" />
    </Svg>
  );
}

export function IconCaretRight(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M8.5 5 15.5 12 8.5 19" />
    </Svg>
  );
}

export function IconExternal(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M10 4H4V20H20V14M13 4H20V11M19.5 4.5 11 13" />
    </Svg>
  );
}

export function IconSpinner(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M12 3A9 9 0 1 0 21 12" />
    </Svg>
  );
}

export function IconInfo(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 2.5H21.5V17L17 21.5H2.5Z" /><path d="M10.75 10H13.25V17.5H10.75ZM10.75 6H13.25V8.5H10.75Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconWarning(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M12 3 22 20.5H2Z" /><path d="M10.75 9H13.25V14.5H10.75ZM10.75 16H13.25V18.5H10.75Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconPhone(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M3 3H9L10.5 8 8 10 14 16 16 13.5 21 15V21H17L3 7Z" fill="currentColor" stroke="none" /><path d="M15 3H21V5H17.66Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M17.5 6H21V8H20.16Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconMail(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 5H21.5V19H2.5Z" /><path d="M3 6 12 13 21 6" />
    </Svg>
  );
}

export function IconPin(props: IconProps) {
  return (
    <Svg {...props}>
      <path fillRule="evenodd" d="M4.5 2.5H19.5V13L12 22 4.5 13ZM9.5 6.5V11.5H14.5V6.5Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconClock(props: IconProps) {
  return (
    <Svg {...props}>
      <circle cx="12" cy="12" r="9" /><path d="M12 6.5V12.5H16.5" />
    </Svg>
  );
}

export function IconChat(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 3.5H21.5V16H10L5 21V16H2.5Z" /><path d="M7 8.5H17V10.5H7ZM7 12H13V14H7Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconCar(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M0.5 7.5H6V9.5H3.16Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M2 10.5H6V12.5H4.66Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M3.5 13.5H6V15.5H6.16Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path fillRule="evenodd" d="M6.5 18.5V12L9.5 11.2 12.2 6H19.2L22.4 11.2 23.5 12V18.5ZM13.5 8.2 12.2 10.8H15.6V8.2ZM17.4 8.2V10.8H20.3L18.7 8.2Z" fill="currentColor" stroke="none" /><circle cx="11" cy="18.5" r="3" fill="var(--icon-knock, var(--bg))" stroke="none" /><circle cx="19.5" cy="18.5" r="3" fill="var(--icon-knock, var(--bg))" stroke="none" /><circle cx="11" cy="18.5" r="1.75" fill="currentColor" stroke="none" /><circle cx="19.5" cy="18.5" r="1.75" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconLicence(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 5H21.5V19H2.5Z" /><path d="M5.5 8.5H10V15.5H5.5Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path fillRule="evenodd" d="M12.5 8H16.6L18 9.4V11.2L17.2 12 18 12.8V14.6L16.6 16H12.5ZM14.4 9.7V11.2H16.1V9.7ZM14.4 12.8V14.3H16.1V12.8Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconLicenceReturn(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 10H15.5V21H2.5Z" /><path d="M5 13H9V18H5Z" fill="currentColor" stroke="none" /><path d="M11 5.5H20.5V13.5H17M19 10.5 16 13.5 19 16.5" stroke="var(--icon-accent, currentColor)" />
    </Svg>
  );
}

export function IconTram(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M9 2.5H15M12 2.5V5" /><path fillRule="evenodd" d="M7.5 5H16.5L19 7.5V19.5H5V7.5ZM7.5 8V12.5H16.5V8Z" fill="currentColor" stroke="none" /><path d="M7 15H9.5V17H7ZM14.5 15H17V17H14.5Z" fill="var(--icon-knock, var(--bg))" stroke="none" /><path d="M3 21.5H21V23H3Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconParking(props: IconProps) {
  return (
    <Svg {...props}>
      <path fillRule="evenodd" d="M2 2H22V17.5L16 22H2ZM8 6V18H11V14H14L16.5 11.5V8.5L14 6ZM11 8.8V11.2H13.5V8.8Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconWheel(props: IconProps) {
  return (
    <Svg {...props}>
      <circle cx="12" cy="12" r="9" /><path d="M3.5 11H8.5M15.5 11H20.5M12 14.5V20.5" /><path d="M9.5 9.5H14.5V14.5H9.5Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconTraining(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 3.5H21.5V16H2.5Z" /><path d="M12 16V21.5M7.5 21.5 12 17.5 16.5 21.5" /><path d="M7 6.5H18V8.5H9.66Z" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M10 9.75H18V11.75H12.66Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconCity(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2 21V12H5V8L6.5 3.5 8 8V12H10V9.5H14V12H16V8L17.5 3.5 19 8V12H22V21Z" fill="currentColor" stroke="none" /><path d="M4.5 15H6.5V17.5H4.5ZM11 13H13V15.5H11ZM17.5 15H19.5V17.5H17.5Z" fill="var(--icon-knock, var(--bg))" stroke="none" />
    </Svg>
  );
}

export function IconCalendar(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M3 5.5H21V21H3Z" /><path d="M3 5.5H21V9.5H3Z" fill="currentColor" stroke="none" /><path d="M8 2.5V6M16 2.5V6" /><path d="M8 15 11 18 16.5 12.5" stroke="var(--icon-accent, currentColor)" />
    </Svg>
  );
}

export function IconCoins(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2 18.5H15V21.5H2ZM3.5 14.5H16.5V17.5H3.5ZM5 10.5H13.5V13.5H5Z" fill="currentColor" stroke="none" /><circle cx="17" cy="7.5" r="5" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M16 5H18V10H16Z" fill="var(--icon-knock, var(--bg))" stroke="none" />
    </Svg>
  );
}

export function IconReceipt(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M5 2.5H19V21L16.5 19.25 14 21 11.5 19.25 9 21 6.5 19.25 5 20.25Z" /><path d="M8.5 7.5H15.5M8.5 11H15.5M8.5 14.5H12.5" />
    </Svg>
  );
}

export function IconDocument(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M5 2.5H14.5L19 7V21.5H5Z" /><path d="M8.5 11.5H15.5M8.5 15H15.5M8.5 18.5H12.5" /><path d="M13.5 2.5H14.5L19 7V8H13.5Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconMedical(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 2.5H21.5V17L17 21.5H2.5Z" /><path d="M10.5 6H13.5V10.5H18V13.5H13.5V18H10.5V13.5H6V10.5H10.5Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconIdCard(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 5H21.5V19H2.5Z" /><path d="M5.5 8.5H10.5V15.5H5.5Z" fill="currentColor" stroke="none" /><path d="M13 10H18.5M13 13.5H18.5" />
    </Svg>
  );
}

export function IconCalm(props: IconProps) {
  return (
    <Svg {...props}>
      <circle cx="12" cy="12" r="9" /><path d="M8 8.5H10.5V11H8ZM13.5 8.5H16V11H13.5Z" fill="currentColor" stroke="none" /><path d="M7.5 14 12 16.5 16.5 14" stroke="var(--icon-accent, currentColor)" />
    </Svg>
  );
}

export function IconFriends(props: IconProps) {
  return (
    <Svg {...props}>
      <circle cx="17" cy="7" r="2.75" fill="var(--icon-accent, currentColor)" stroke="none" /><path d="M13.5 11.5H20.5L22.5 20H15Z" fill="var(--icon-accent, currentColor)" stroke="none" /><circle cx="8" cy="6" r="3.25" fill="currentColor" stroke="none" /><path d="M3 11H13L15 21H1Z" fill="currentColor" stroke="none" />
    </Svg>
  );
}

export function IconHeart(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M12 21 2.5 11.5V6.5L5.5 3.5H9L12 6.5 15 3.5H18.5L21.5 6.5V11.5Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconBriefcase(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 7H21.5V20.5H2.5Z" /><path d="M9 7V4H15V7" /><path d="M2.5 11.5H21.5V13.5H2.5Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}

export function IconHome(props: IconProps) {
  return (
    <Svg {...props}>
      <path d="M2.5 11.5 12 3.5 21.5 11.5" /><path d="M5 9.5V20.5H19V9.5" /><path d="M10 14H14V20.5H10Z" fill="var(--icon-accent, currentColor)" stroke="none" />
    </Svg>
  );
}
